AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Origin For Cloudfront"

Parameters:
  BucketName:
    Description: S3 bucket name. Same with domain name.
    Type: String

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: "Name"
          Value: "bnchen.link"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true

Outputs:
  BucketName:
    Description: S3 bucket name.
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName
